import type { Hospital } from "@/types";

export const CONFIG = {
  N8N_BOOKING_WEBHOOK: "https://babarsher.app.n8n.cloud/webhook/new-appointment",
  N8N_RESCHEDULE_WEBHOOK: "https://babarsher.app.n8n.cloud/webhook/reschedule",
  GROQ_API_KEY: process.env.NEXT_PUBLIC_GROQ_API_KEY || "",
  SHEET_ID: "1tZ9X3mVs72Em6aT1EKX46J4Ju3ZDQAjSf_B9ykPrnU0",
  API: {
    TIMEOUT_MS: 10000,
    MAX_RETRIES: 2,
    RETRY_DELAY: 1500,
  },
  VALIDATION: {
    patientName: {
      required: true,
      minLength: 3,
      maxLength: 80,
      pattern: /^[a-zA-Z\u0600-\u06FF\s.'\\-]+$/,
      label: "Patient Name",
      messages: {
        required: "Patient name is required.",
        minLength: "Name must be at least 3 characters.",
        maxLength: "Name must be under 80 characters.",
        pattern: "Name may only contain letters, spaces, dots, hyphens.",
      },
    },
    phone: {
      required: true,
      pattern: /^(\+92|0092|0)?3[0-9]{9}$|^\+92\s?3[0-9]{2}[\s-]?[0-9]{7}$/,
      label: "Phone Number",
      messages: {
        required: "Phone number is required.",
        pattern: "Enter a valid Pakistani mobile number (e.g. 0300-1234567).",
      },
    },
    email: {
      required: true,
      pattern: /^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/,
      label: "Email Address",
      messages: {
        required: "Email address is required.",
        pattern: "Enter a valid email address.",
      },
    },
    date: {
      required: true,
      label: "Appointment Date",
      messages: {
        required: "Please select an appointment date.",
        pastDate: "Appointment date cannot be in the past.",
        tooFarAhead: "Cannot book more than 90 days in advance.",
      },
    },
    timeSlot: {
      required: true,
      label: "Time Slot",
      messages: { required: "Please select a time slot." },
    },
    visitType: {
      required: true,
      label: "Visit Type",
      messages: { required: "Please select a visit type." },
    },
    reason: {
      required: false,
      maxLength: 300,
      label: "Reason for Visit",
      messages: { maxLength: "Reason must be under 300 characters." },
    },
  },
} as const;

// ── Hospitals ──────────────────────────────────────────────────────────────
// AKUH doctors are loaded dynamically from /public/agha_khan_doctors.json
export const HOSPITALS_BASE: Omit<Hospital, "doctors">[] = [
  {
    id: 1,
    name: "Aga Khan University Hospital",
    shortName: "AKUH",
    location: "Stadium Road, Karachi",
    type: "Tertiary Care",
    rating: 4.9,
    tag: "Top Rated",
    featured: true,
    comingSoon: false,
    specialties: ["Cardiology", "Neurology", "Orthopaedic Surgery", "Gastroenterology", "Dermatology", "Endocrinology", "Psychiatry", "Pulmonology", "Internal Medicine", "Urology", "Ophthalmology", "ENT", "Paediatrics", "+ 48 more"],
    doctorCount: 437,
    emoji: "🏥",
    phone: "+92 21 3486 1234",
  },
  {
    id: 2,
    name: "Shaukat Khanum Cancer Centre",
    shortName: "SKMCH",
    location: "Johar Town, Lahore",
    type: "Oncology Centre",
    rating: 4.8,
    tag: "Specialist",
    featured: false,
    comingSoon: false,
    specialties: ["Oncology", "Radiology", "Surgery", "Palliative Care"],
    doctorCount: 180,
    emoji: "🔬",
    phone: "+92 42 3590 5000",
  },
  {
    id: 3,
    name: "Liaquat National Hospital",
    shortName: "LNH",
    location: "Karachi, Sindh",
    type: "Multi-Specialty",
    rating: 4.6,
    tag: "Established",
    featured: false,
    comingSoon: false,
    specialties: ["Cardiology", "Gastroenterology", "Dermatology", "ENT"],
    doctorCount: 310,
    emoji: "💊",
    phone: "+92 21 3412 6000",
  },
  {
    id: 4,
    name: "South City Hospital",
    shortName: "SCH",
    location: "Clifton, Karachi",
    type: "Multi-Specialty",
    rating: 4.5,
    tag: "Modern",
    featured: false,
    comingSoon: false,
    specialties: ["Ophthalmology", "Urology", "Obstetrics", "Psychiatry"],
    doctorCount: 140,
    emoji: "🏨",
    phone: "+92 21 3587 0011",
  },
  {
    id: 5,
    name: "Peshawar General Hospital",
    shortName: "PGH",
    location: "Peshawar, KPK",
    type: "Government Tertiary",
    rating: 4.3,
    tag: "Coming Soon",
    featured: false,
    comingSoon: true,
    specialties: ["General Surgery", "Internal Medicine", "Pediatrics"],
    doctorCount: 0,
    emoji: "🏛️",
    phone: "",
  },
  {
    id: 6,
    name: "Islamabad Medical Complex",
    shortName: "IMC",
    location: "Blue Area, Islamabad",
    type: "Private Multi-Specialty",
    rating: 4.7,
    tag: "Coming Soon",
    featured: false,
    comingSoon: true,
    specialties: ["Cardiology", "Neurology", "Endocrinology", "Rheumatology"],
    doctorCount: 0,
    emoji: "🏢",
    phone: "",
  },
];

export const STATIC_DOCTORS: Record<number, import("@/types").Doctor[]> = {
  2: [
    { id: 201, name: "Dr. Asim Khan",     spec: "Surgical Oncology",   qual: "MBBS, FRCS, PhD Oncology",    avail: "Mon–Thu", initials: "AK", slots: ["9:00 AM","1:00 PM","3:00 PM"] },
    { id: 202, name: "Dr. Lubna Tasneem", spec: "Radiation Oncology",  qual: "MBBS, FCPS Oncology",         avail: "Tue–Sat", initials: "LT", slots: ["10:00 AM","2:30 PM"] },
    { id: 203, name: "Dr. Zafar Ali",     spec: "Medical Oncology",    qual: "MBBS, MRCP, MSc Oncology",    avail: "Mon–Fri", initials: "ZA", slots: ["9:30 AM","11:30 AM","4:00 PM"] },
    { id: 204, name: "Dr. Rabia Qureshi", spec: "Palliative Care",     qual: "MBBS, FCPS, Fellowship UK",   avail: "Wed–Fri", initials: "RQ", slots: ["10:00 AM","3:30 PM"] },
  ],
  3: [
    { id: 301, name: "Dr. Hassan Raza",  spec: "Cardiology",       qual: "MBBS, FRCP, FESC",           avail: "Mon–Wed", initials: "HR", slots: ["9:00 AM","11:00 AM","3:30 PM"] },
    { id: 302, name: "Dr. Amina Shah",   spec: "Gastroenterology", qual: "MBBS, FCPS GI",              avail: "Tue–Fri", initials: "AS", slots: ["10:30 AM","2:00 PM","4:30 PM"] },
    { id: 303, name: "Dr. Bilal Yousuf", spec: "Dermatology",      qual: "MBBS, FCPS Dermatology",     avail: "Mon–Thu", initials: "BY", slots: ["9:30 AM","12:00 PM","5:00 PM"] },
  ],
  4: [
    { id: 401, name: "Dr. Sara Baig",   spec: "Obstetrics & Gynecology", qual: "MBBS, MCOG, DFFP",    avail: "Mon–Fri", initials: "SB", slots: ["9:00 AM","10:30 AM","2:30 PM"] },
    { id: 402, name: "Dr. Kamran Noor", spec: "Urology",                 qual: "MBBS, FRCS Urology",  avail: "Tue–Sat", initials: "KN", slots: ["11:00 AM","3:00 PM","4:30 PM"] },
  ],
};
